server:
  port: 8088
  servlet:
    context-path: /
app:
  version: "0.0.1"

## SWAGGER
#springfox:
#  documentation:
#    swagger:
#      v2:
#        path: /api-docs  

# Time cache 
my:
  fixed: 
    delay:
      prop: 5000

endpoints:
  doc: error_codes.html

# SPRING DATA
        
## Dynatrace
#management:
#  server:
#    port: 8090
#  metrics:
#    export:
#      dynatrace:  
#        uri: https://vuu92847.live.dynatrace.com
#        api-token: PXBtS4DETU2L16GtpV9Zx
#        device-id: transactionhistory
#        group: claroflex-BFF
#        step: 1m
#        enabled: true
#        connect-timeout: 2s     
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    metrics:
#      enabled: true
#    health:
#      show-details: ALWAYS